// frontend/src/components/header.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useSongStore } from '@/stores/song'
import Info from '@/components/info.vue'

const term = ref('')
const song = useSongStore()
</script>
<template>
  <div class="sticky-top header">
    <nav class="py-1">
      <div class="container d-flex flex-wrap">
        <ul class="nav mx-auto mx-md-0 me-md-auto">
          <li class="nav-item">
            <info :song="song.title" />
          </li>
        </ul>
        <ul class="nav mx-auto mx-md-0 ms-md-auto">
          <li class="nav-item">            
            <slot />
          </li>
        </ul>
      </div>
    </nav>
    <header class="py-2 text-white">
      <div class="container d-flex flex-wrap align-content-center justify-content-center">
        <router-link to="/" class="d-flex align-items-center align-content-center mb-3 mb-lg-0 me-lg-auto text-white text-decoration-none">
          <img width="46" height="46" class="me-2" src="/images/logotipo.svg" alt="Som do Mato">
          <span class="fs-4">Som do Mato</span>
        </router-link>
        <div class="col-12 col-lg-auto mb-3 mb-lg-0 text-center">
          <router-link to="/entrar" class="btn btn-outline-light me-2">Entrar</router-link>
          <router-link to="/cadastro" class="btn btn-warning">Cadastro</router-link>
        </div>
      </div>
    </header>
  </div>
</template>
<style>
svg {
  cursor: pointer;
}
</style>

// src/components/Header.tsx
import Link from "next/link";
import Image from "next/image";
import Navbar from "./Navbar";
import Player from "./Player";

export default function Header() {
  return (
    <header className="md:flex md:items-center md:justify-between sticky z-50 bg-background top-0 p-4 border-b-3 border-black/50">
      <Link 
        href="/"
        className="flex items-center gap-4 font-bold text-2xl"
      >
        <Image
          src="/images/logotipo.svg"
          alt="Rádio Som do Mato"
          width={50}
          height={50}
          className="shrink-0"
        />
        <span className="shrink-0">
          Rádio Som do Mato
        </span>
      </Link>
      <div className="flex gap-2">
        <Navbar />
        <Player />
      </div>
    </header>
  );
}
